name: todos_data_source
description: A generic interface for managing todos.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
dependencies:
  equatable: ^2.0.5
